ARG BASE_IMAGE
ARG VERSION
FROM ${BASE_IMAGE}:${VERSION}

LABEL org.opencontainers.image.source="https://github.com/hyperweb-io/starship"

# Set up dependencies
ENV PACKAGES curl make bash jq sed

# Install minimum necessary dependencies
RUN apt-get update --yes && \
    apt-get install $PACKAGES --no-install-recommends --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

ARG VERSION

# Verify installation
RUN solana --version
